// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/pocketzworld/lurus-switch/provider-service/internal/biz"
	"github.com/pocketzworld/lurus-switch/provider-service/internal/conf"
	"github.com/pocketzworld/lurus-switch/provider-service/internal/data"
	"github.com/pocketzworld/lurus-switch/provider-service/internal/server"
	"github.com/pocketzworld/lurus-switch/provider-service/internal/service"
	"go.uber.org/zap"
)

// wireApp initializes the application with Wire
func wireApp(bootstrap *conf.Bootstrap, logger *zap.Logger) (*App, func(), error) {
	dataData, cleanup, err := data.NewData(&bootstrap.Data, logger)
	if err != nil {
		return nil, nil, err
	}

	providerRepo := data.NewProviderRepo(dataData, logger)
	providerCache := data.NewProviderCache(dataData, logger)
	providerUsecase := biz.NewProviderUsecase(providerRepo, providerCache, logger)
	providerService := service.NewProviderService(providerUsecase, logger)
	httpServer := server.NewHTTPServer(&bootstrap.Server, providerService, logger)

	app := newApp(httpServer, logger)

	return app, cleanup, nil
}
