// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/pocketzworld/lurus-switch/log-service/internal/biz"
	"github.com/pocketzworld/lurus-switch/log-service/internal/conf"
	"github.com/pocketzworld/lurus-switch/log-service/internal/consumer"
	"github.com/pocketzworld/lurus-switch/log-service/internal/data"
	"github.com/pocketzworld/lurus-switch/log-service/internal/server"
	"github.com/pocketzworld/lurus-switch/log-service/internal/service"
	"go.uber.org/zap"
)

// wireApp initializes the application with Wire
func wireApp(bootstrap *conf.Bootstrap, logger *zap.Logger) (*App, func(), error) {
	dataData, cleanup, err := data.NewData(&bootstrap.Data, logger)
	if err != nil {
		return nil, nil, err
	}

	logRepo := data.NewLogRepo(dataData, logger)
	logUsecase := biz.NewLogUsecase(logRepo, logger)
	logService := service.NewLogService(logUsecase, logger)
	httpServer := server.NewHTTPServer(&bootstrap.Server, logService, logger)

	natsConsumer, natsCleanup, err := consumer.NewNATSConsumer(logUsecase, &bootstrap.NATS, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}

	app := newApp(httpServer, natsConsumer, logger)

	return app, func() {
		natsCleanup()
		cleanup()
	}, nil
}
