package generator

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"lurus-switch/internal/config"
)

// === Constructor Tests ===

func TestNewCodexGenerator(t *testing.T) {
	gen := NewCodexGenerator()
	if gen == nil {
		t.Error("NewCodexGenerator should return non-nil generator")
	}
}

// === GenerateString Tests ===

func TestCodexGeneratorGenerateString(t *testing.T) {
	gen := NewCodexGenerator()
	cfg := config.NewCodexConfig()
	cfg.Model = "o4-mini"
	cfg.ApprovalMode = "suggest"

	content, err := gen.GenerateString(cfg)
	if err != nil {
		t.Fatalf("Failed to generate string: %v", err)
	}

	if !strings.Contains(content, "o4-mini") {
		t.Error("Generated content should contain model name")
	}

	if !strings.Contains(content, "suggest") {
		t.Error("Generated content should contain approval mode")
	}
}

func TestCodexGeneratorGenerateString_Header(t *testing.T) {
	gen := NewCodexGenerator()
	cfg := config.NewCodexConfig()

	content, err := gen.GenerateString(cfg)
	if err != nil {
		t.Fatalf("Failed to generate string: %v", err)
	}

	if !strings.Contains(content, "# Codex CLI Configuration") {
		t.Error("Generated content should contain header comment")
	}
	if !strings.Contains(content, "# Generated by Lurus Switch") {
		t.Error("Generated content should contain generator comment")
	}
}

func TestCodexGeneratorGenerateString_AllFields(t *testing.T) {
	gen := NewCodexGenerator()
	cfg := &config.CodexConfig{
		Model:        "gpt-4",
		APIKey:       "sk-test",
		ApprovalMode: "auto-edit",
		Provider: config.CodexProvider{
			Type:            "azure",
			BaseURL:         "https://my.azure.com",
			AzureDeployment: "gpt-4",
			AzureAPIVersion: "2024-01-01",
		},
		Security: config.CodexSecurity{
			NetworkAccess: "full",
			FileAccess: config.CodexFileAccess{
				AllowedDirs:    []string{"/home", "/tmp"},
				DeniedPatterns: []string{"*.key"},
			},
			CommandExecution: config.CodexCommandExecution{
				Enabled:         true,
				AllowedCommands: []string{"git*"},
			},
		},
		MCP: config.CodexMCP{
			Enabled: true,
			Servers: []config.CodexMCPServer{
				{Name: "fs", Command: "mcp-fs"},
			},
		},
		Sandbox: config.CodexSandbox{
			Enabled: true,
			Type:    "seatbelt",
		},
		History: config.CodexHistory{
			Enabled:    true,
			MaxEntries: 500,
		},
	}

	content, err := gen.GenerateString(cfg)
	if err != nil {
		t.Fatalf("Failed to generate string: %v", err)
	}

	expectedFields := []string{"gpt-4", "auto-edit", "azure", "full", "seatbelt"}
	for _, field := range expectedFields {
		if !strings.Contains(content, field) {
			t.Errorf("Generated content should contain '%s'", field)
		}
	}
}

func TestCodexGeneratorGenerateString_TOMLFormat(t *testing.T) {
	gen := NewCodexGenerator()
	cfg := config.NewCodexConfig()
	cfg.Model = "o4-mini"

	content, err := gen.GenerateString(cfg)
	if err != nil {
		t.Fatalf("Failed to generate string: %v", err)
	}

	// TOML should have = for assignments
	if !strings.Contains(content, "model = ") {
		t.Error("Generated content should be valid TOML with '=' assignments")
	}
}

// === Generate Tests ===

func TestCodexGeneratorGenerate(t *testing.T) {
	gen := NewCodexGenerator()
	cfg := config.NewCodexConfig()

	tmpDir, err := os.MkdirTemp("", "codex-test-*")
	if err != nil {
		t.Fatalf("Failed to create temp dir: %v", err)
	}
	defer os.RemoveAll(tmpDir)

	outputPath, err := gen.Generate(cfg, tmpDir)
	if err != nil {
		t.Fatalf("Failed to generate: %v", err)
	}

	if filepath.Base(outputPath) != "config.toml" {
		t.Errorf("Expected config.toml, got %s", filepath.Base(outputPath))
	}

	// Verify file exists
	if _, err := os.Stat(outputPath); os.IsNotExist(err) {
		t.Error("Output file was not created")
	}
}

func TestCodexGeneratorGenerate_CreatesDir(t *testing.T) {
	gen := NewCodexGenerator()
	cfg := config.NewCodexConfig()

	tmpDir := t.TempDir()
	outputDir := filepath.Join(tmpDir, "nested", "dir")

	_, err := gen.Generate(cfg, outputDir)
	if err != nil {
		t.Fatalf("Failed to generate: %v", err)
	}

	if _, err := os.Stat(outputDir); os.IsNotExist(err) {
		t.Error("Output directory should be created")
	}
}

func TestCodexGeneratorGenerate_FileContent(t *testing.T) {
	gen := NewCodexGenerator()
	cfg := config.NewCodexConfig()
	cfg.Model = "gpt-4-turbo"

	tmpDir := t.TempDir()
	outputPath, err := gen.Generate(cfg, tmpDir)
	if err != nil {
		t.Fatalf("Failed to generate: %v", err)
	}

	content, err := os.ReadFile(outputPath)
	if err != nil {
		t.Fatalf("Failed to read output file: %v", err)
	}

	if !strings.Contains(string(content), "gpt-4-turbo") {
		t.Error("Output file should contain model name")
	}
}

func TestCodexGeneratorGenerate_Permissions(t *testing.T) {
	gen := NewCodexGenerator()
	cfg := config.NewCodexConfig()

	tmpDir := t.TempDir()
	outputPath, err := gen.Generate(cfg, tmpDir)
	if err != nil {
		t.Fatalf("Failed to generate: %v", err)
	}

	info, err := os.Stat(outputPath)
	if err != nil {
		t.Fatalf("Failed to stat output file: %v", err)
	}

	// Check file is readable (0644 or similar)
	if info.Mode().Perm()&0400 == 0 {
		t.Error("Output file should be readable")
	}
}

// === GenerateWithInstructions Tests ===

func TestCodexGeneratorGenerateWithInstructions(t *testing.T) {
	gen := NewCodexGenerator()
	cfg := config.NewCodexConfig()

	tmpDir := t.TempDir()
	files, err := gen.GenerateWithInstructions(cfg, "Custom instructions", tmpDir)
	if err != nil {
		t.Fatalf("Failed to generate: %v", err)
	}

	if len(files) != 2 {
		t.Errorf("Expected 2 files, got %d", len(files))
	}

	// Check instructions file exists
	instructionsPath := filepath.Join(tmpDir, "instructions.md")
	if _, err := os.Stat(instructionsPath); os.IsNotExist(err) {
		t.Error("Instructions file should be created")
	}

	// Check content
	content, err := os.ReadFile(instructionsPath)
	if err != nil {
		t.Fatalf("Failed to read instructions file: %v", err)
	}

	if string(content) != "Custom instructions" {
		t.Error("Instructions file should contain custom instructions")
	}
}

func TestCodexGeneratorGenerateWithInstructions_EmptyInstructions(t *testing.T) {
	gen := NewCodexGenerator()
	cfg := config.NewCodexConfig()

	tmpDir := t.TempDir()
	files, err := gen.GenerateWithInstructions(cfg, "", tmpDir)
	if err != nil {
		t.Fatalf("Failed to generate: %v", err)
	}

	// Should only create config.toml, not instructions.md
	if len(files) != 1 {
		t.Errorf("Expected 1 file when instructions empty, got %d", len(files))
	}

	// Check instructions file does not exist
	instructionsPath := filepath.Join(tmpDir, "instructions.md")
	if _, err := os.Stat(instructionsPath); !os.IsNotExist(err) {
		t.Error("Instructions file should not be created when empty")
	}
}

// === Validate Tests ===

func TestCodexGeneratorValidate(t *testing.T) {
	gen := NewCodexGenerator()

	// Valid config
	validCfg := config.NewCodexConfig()
	if err := gen.Validate(validCfg); err != nil {
		t.Errorf("Valid config should not return error: %v", err)
	}

	// Invalid approval mode
	invalidCfg := config.NewCodexConfig()
	invalidCfg.ApprovalMode = "invalid"
	if err := gen.Validate(invalidCfg); err == nil {
		t.Error("Invalid approval mode should return error")
	}
}

func TestCodexGeneratorValidate_EmptyModel(t *testing.T) {
	gen := NewCodexGenerator()
	cfg := config.NewCodexConfig()
	cfg.Model = ""

	err := gen.Validate(cfg)
	if err == nil {
		t.Error("Empty model should return error")
	}
	if !strings.Contains(err.Error(), "model is required") {
		t.Error("Error should mention model is required")
	}
}

func TestCodexGeneratorValidate_AllApprovalModes(t *testing.T) {
	gen := NewCodexGenerator()

	validModes := []string{"suggest", "auto-edit", "full-auto"}
	for _, mode := range validModes {
		t.Run(mode, func(t *testing.T) {
			cfg := config.NewCodexConfig()
			cfg.ApprovalMode = mode

			if err := gen.Validate(cfg); err != nil {
				t.Errorf("Approval mode '%s' should be valid: %v", mode, err)
			}
		})
	}
}

func TestCodexGeneratorValidate_InvalidApprovalMode(t *testing.T) {
	gen := NewCodexGenerator()
	cfg := config.NewCodexConfig()
	cfg.ApprovalMode = "manual"

	err := gen.Validate(cfg)
	if err == nil {
		t.Error("Invalid approval mode should return error")
	}
	if !strings.Contains(err.Error(), "invalid approval mode") {
		t.Error("Error should mention invalid approval mode")
	}
}

func TestCodexGeneratorValidate_AllProviders(t *testing.T) {
	gen := NewCodexGenerator()

	validProviders := []string{"openai", "azure", "openrouter", "custom"}
	for _, provider := range validProviders {
		t.Run(provider, func(t *testing.T) {
			cfg := config.NewCodexConfig()
			cfg.Provider.Type = provider
			// Azure requires deployment
			if provider == "azure" {
				cfg.Provider.AzureDeployment = "test"
			}

			if err := gen.Validate(cfg); err != nil {
				t.Errorf("Provider '%s' should be valid: %v", provider, err)
			}
		})
	}
}

func TestCodexGeneratorValidate_InvalidProvider(t *testing.T) {
	gen := NewCodexGenerator()
	cfg := config.NewCodexConfig()
	cfg.Provider.Type = "invalid"

	err := gen.Validate(cfg)
	if err == nil {
		t.Error("Invalid provider should return error")
	}
	if !strings.Contains(err.Error(), "invalid provider type") {
		t.Error("Error should mention invalid provider type")
	}
}

func TestCodexGeneratorValidate_Azure_RequiresDeployment(t *testing.T) {
	gen := NewCodexGenerator()
	cfg := config.NewCodexConfig()
	cfg.Provider.Type = "azure"
	cfg.Provider.AzureDeployment = ""

	err := gen.Validate(cfg)
	if err == nil {
		t.Error("Azure without deployment should return error")
	}
	if !strings.Contains(err.Error(), "azure_deployment is required") {
		t.Error("Error should mention azure_deployment is required")
	}
}

func TestCodexGeneratorValidate_AllNetworkAccess(t *testing.T) {
	gen := NewCodexGenerator()

	validAccess := []string{"off", "local", "full"}
	for _, access := range validAccess {
		t.Run(access, func(t *testing.T) {
			cfg := config.NewCodexConfig()
			cfg.Security.NetworkAccess = access

			if err := gen.Validate(cfg); err != nil {
				t.Errorf("Network access '%s' should be valid: %v", access, err)
			}
		})
	}
}

func TestCodexGeneratorValidate_InvalidNetworkAccess(t *testing.T) {
	gen := NewCodexGenerator()
	cfg := config.NewCodexConfig()
	cfg.Security.NetworkAccess = "unlimited"

	err := gen.Validate(cfg)
	if err == nil {
		t.Error("Invalid network access should return error")
	}
	if !strings.Contains(err.Error(), "invalid network access") {
		t.Error("Error should mention invalid network access")
	}
}
