// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplySelfUpdate() {
  return window['go']['main']['App']['ApplySelfUpdate']();
}

export function CheckAllUpdates() {
  return window['go']['main']['App']['CheckAllUpdates']();
}

export function CheckBunInstalled() {
  return window['go']['main']['App']['CheckBunInstalled']();
}

export function CheckNodeInstalled() {
  return window['go']['main']['App']['CheckNodeInstalled']();
}

export function CheckSelfUpdate() {
  return window['go']['main']['App']['CheckSelfUpdate']();
}

export function ConfigureAllProxy() {
  return window['go']['main']['App']['ConfigureAllProxy']();
}

export function DeleteClaudeConfig(arg1) {
  return window['go']['main']['App']['DeleteClaudeConfig'](arg1);
}

export function DeleteCodexConfig(arg1) {
  return window['go']['main']['App']['DeleteCodexConfig'](arg1);
}

export function DeleteGeminiConfig(arg1) {
  return window['go']['main']['App']['DeleteGeminiConfig'](arg1);
}

export function DetectAllTools() {
  return window['go']['main']['App']['DetectAllTools']();
}

export function DownloadCodexBinary(arg1) {
  return window['go']['main']['App']['DownloadCodexBinary'](arg1);
}

export function ExportClaudeConfig(arg1) {
  return window['go']['main']['App']['ExportClaudeConfig'](arg1);
}

export function ExportCodexConfig(arg1) {
  return window['go']['main']['App']['ExportCodexConfig'](arg1);
}

export function ExportGeminiConfig(arg1) {
  return window['go']['main']['App']['ExportGeminiConfig'](arg1);
}

export function GenerateClaudeConfig(arg1) {
  return window['go']['main']['App']['GenerateClaudeConfig'](arg1);
}

export function GenerateCodexConfig(arg1) {
  return window['go']['main']['App']['GenerateCodexConfig'](arg1);
}

export function GenerateGeminiConfig(arg1) {
  return window['go']['main']['App']['GenerateGeminiConfig'](arg1);
}

export function GetAllToolConfigPaths() {
  return window['go']['main']['App']['GetAllToolConfigPaths']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetConfigDir() {
  return window['go']['main']['App']['GetConfigDir']();
}

export function GetDefaultClaudeConfig() {
  return window['go']['main']['App']['GetDefaultClaudeConfig']();
}

export function GetDefaultCodexConfig() {
  return window['go']['main']['App']['GetDefaultCodexConfig']();
}

export function GetDefaultGeminiConfig() {
  return window['go']['main']['App']['GetDefaultGeminiConfig']();
}

export function GetProxySettings() {
  return window['go']['main']['App']['GetProxySettings']();
}

export function GetToolConfigPath(arg1) {
  return window['go']['main']['App']['GetToolConfigPath'](arg1);
}

export function InstallAllTools() {
  return window['go']['main']['App']['InstallAllTools']();
}

export function InstallBun() {
  return window['go']['main']['App']['InstallBun']();
}

export function InstallTool(arg1) {
  return window['go']['main']['App']['InstallTool'](arg1);
}

export function ListClaudeConfigs() {
  return window['go']['main']['App']['ListClaudeConfigs']();
}

export function ListCodexConfigs() {
  return window['go']['main']['App']['ListCodexConfigs']();
}

export function ListGeminiConfigs() {
  return window['go']['main']['App']['ListGeminiConfigs']();
}

export function LoadClaudeConfig(arg1) {
  return window['go']['main']['App']['LoadClaudeConfig'](arg1);
}

export function LoadCodexConfig(arg1) {
  return window['go']['main']['App']['LoadCodexConfig'](arg1);
}

export function LoadGeminiConfig(arg1) {
  return window['go']['main']['App']['LoadGeminiConfig'](arg1);
}

export function OpenConfigDir() {
  return window['go']['main']['App']['OpenConfigDir']();
}

export function OpenToolConfigDir(arg1) {
  return window['go']['main']['App']['OpenToolConfigDir'](arg1);
}

export function PackageClaudeConfig(arg1) {
  return window['go']['main']['App']['PackageClaudeConfig'](arg1);
}

export function ReadToolConfig(arg1) {
  return window['go']['main']['App']['ReadToolConfig'](arg1);
}

export function SaveClaudeConfig(arg1, arg2) {
  return window['go']['main']['App']['SaveClaudeConfig'](arg1, arg2);
}

export function SaveCodexConfig(arg1, arg2) {
  return window['go']['main']['App']['SaveCodexConfig'](arg1, arg2);
}

export function SaveGeminiConfig(arg1, arg2) {
  return window['go']['main']['App']['SaveGeminiConfig'](arg1, arg2);
}

export function SaveProxySettings(arg1) {
  return window['go']['main']['App']['SaveProxySettings'](arg1);
}

export function SaveToolConfig(arg1, arg2) {
  return window['go']['main']['App']['SaveToolConfig'](arg1, arg2);
}

export function UpdateAllTools() {
  return window['go']['main']['App']['UpdateAllTools']();
}

export function UpdateTool(arg1) {
  return window['go']['main']['App']['UpdateTool'](arg1);
}

export function ValidateClaudeConfig(arg1) {
  return window['go']['main']['App']['ValidateClaudeConfig'](arg1);
}

export function ValidateCodexConfig(arg1) {
  return window['go']['main']['App']['ValidateCodexConfig'](arg1);
}

export function ValidateGeminiConfig(arg1) {
  return window['go']['main']['App']['ValidateGeminiConfig'](arg1);
}
