// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyClaudePreset(arg1) {
  return window['go']['main']['App']['ApplyClaudePreset'](arg1);
}

export function ApplyCodexPreset(arg1) {
  return window['go']['main']['App']['ApplyCodexPreset'](arg1);
}

export function ApplyGeminiPreset(arg1) {
  return window['go']['main']['App']['ApplyGeminiPreset'](arg1);
}

export function ApplyMCPServerToTool(arg1, arg2) {
  return window['go']['main']['App']['ApplyMCPServerToTool'](arg1, arg2);
}

export function ApplySelfUpdate() {
  return window['go']['main']['App']['ApplySelfUpdate']();
}

export function BillingCancelSubscription(arg1) {
  return window['go']['main']['App']['BillingCancelSubscription'](arg1);
}

export function BillingCreateTopUp(arg1, arg2) {
  return window['go']['main']['App']['BillingCreateTopUp'](arg1, arg2);
}

export function BillingGetPlans() {
  return window['go']['main']['App']['BillingGetPlans']();
}

export function BillingGetQuotaSummary() {
  return window['go']['main']['App']['BillingGetQuotaSummary']();
}

export function BillingGetSubscriptions() {
  return window['go']['main']['App']['BillingGetSubscriptions']();
}

export function BillingGetTopUpInfo() {
  return window['go']['main']['App']['BillingGetTopUpInfo']();
}

export function BillingGetUserInfo() {
  return window['go']['main']['App']['BillingGetUserInfo']();
}

export function BillingOpenPaymentURL(arg1) {
  return window['go']['main']['App']['BillingOpenPaymentURL'](arg1);
}

export function BillingRedeemCode(arg1) {
  return window['go']['main']['App']['BillingRedeemCode'](arg1);
}

export function BillingSubscribe(arg1, arg2) {
  return window['go']['main']['App']['BillingSubscribe'](arg1, arg2);
}

export function CheckAllToolHealth() {
  return window['go']['main']['App']['CheckAllToolHealth']();
}

export function CheckAllUpdates() {
  return window['go']['main']['App']['CheckAllUpdates']();
}

export function CheckBunInstalled() {
  return window['go']['main']['App']['CheckBunInstalled']();
}

export function CheckNodeInstalled() {
  return window['go']['main']['App']['CheckNodeInstalled']();
}

export function CheckSelfUpdate() {
  return window['go']['main']['App']['CheckSelfUpdate']();
}

export function CheckToolHealth(arg1) {
  return window['go']['main']['App']['CheckToolHealth'](arg1);
}

export function ClearAllSnapshots() {
  return window['go']['main']['App']['ClearAllSnapshots']();
}

export function ClearAllUserPrompts() {
  return window['go']['main']['App']['ClearAllUserPrompts']();
}

export function ClearToolSnapshots(arg1) {
  return window['go']['main']['App']['ClearToolSnapshots'](arg1);
}

export function ConfigureAllProxy() {
  return window['go']['main']['App']['ConfigureAllProxy']();
}

export function DeleteClaudeConfig(arg1) {
  return window['go']['main']['App']['DeleteClaudeConfig'](arg1);
}

export function DeleteCodexConfig(arg1) {
  return window['go']['main']['App']['DeleteCodexConfig'](arg1);
}

export function DeleteConfigSnapshot(arg1, arg2) {
  return window['go']['main']['App']['DeleteConfigSnapshot'](arg1, arg2);
}

export function DeleteGeminiConfig(arg1) {
  return window['go']['main']['App']['DeleteGeminiConfig'](arg1);
}

export function DeleteMCPPreset(arg1) {
  return window['go']['main']['App']['DeleteMCPPreset'](arg1);
}

export function DeleteNullClawConfig(arg1) {
  return window['go']['main']['App']['DeleteNullClawConfig'](arg1);
}

export function DeletePicoClawConfig(arg1) {
  return window['go']['main']['App']['DeletePicoClawConfig'](arg1);
}

export function DeletePrompt(arg1) {
  return window['go']['main']['App']['DeletePrompt'](arg1);
}

export function DetectAllTools() {
  return window['go']['main']['App']['DetectAllTools']();
}

export function DetectSystemProxy() {
  return window['go']['main']['App']['DetectSystemProxy']();
}

export function DiffConfigSnapshots(arg1, arg2, arg3) {
  return window['go']['main']['App']['DiffConfigSnapshots'](arg1, arg2, arg3);
}

export function DownloadCodexBinary(arg1) {
  return window['go']['main']['App']['DownloadCodexBinary'](arg1);
}

export function ExportClaudeConfig(arg1) {
  return window['go']['main']['App']['ExportClaudeConfig'](arg1);
}

export function ExportCodexConfig(arg1) {
  return window['go']['main']['App']['ExportCodexConfig'](arg1);
}

export function ExportGeminiConfig(arg1) {
  return window['go']['main']['App']['ExportGeminiConfig'](arg1);
}

export function ExportNullClawConfig(arg1) {
  return window['go']['main']['App']['ExportNullClawConfig'](arg1);
}

export function ExportPicoClawConfig(arg1) {
  return window['go']['main']['App']['ExportPicoClawConfig'](arg1);
}

export function ExportPrompts() {
  return window['go']['main']['App']['ExportPrompts']();
}

export function GenerateClaudeConfig(arg1) {
  return window['go']['main']['App']['GenerateClaudeConfig'](arg1);
}

export function GenerateCodexConfig(arg1) {
  return window['go']['main']['App']['GenerateCodexConfig'](arg1);
}

export function GenerateGeminiConfig(arg1) {
  return window['go']['main']['App']['GenerateGeminiConfig'](arg1);
}

export function GenerateNullClawConfig(arg1) {
  return window['go']['main']['App']['GenerateNullClawConfig'](arg1);
}

export function GeneratePicoClawConfig(arg1) {
  return window['go']['main']['App']['GeneratePicoClawConfig'](arg1);
}

export function GetAllToolConfigPaths() {
  return window['go']['main']['App']['GetAllToolConfigPaths']();
}

export function GetAppSettings() {
  return window['go']['main']['App']['GetAppSettings']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetBuiltinMCPPresets() {
  return window['go']['main']['App']['GetBuiltinMCPPresets']();
}

export function GetClaudePresets() {
  return window['go']['main']['App']['GetClaudePresets']();
}

export function GetCodexPresets() {
  return window['go']['main']['App']['GetCodexPresets']();
}

export function GetGeminiPresets() {
  return window['go']['main']['App']['GetGeminiPresets']();
}

export function GetBuiltinPrompts() {
  return window['go']['main']['App']['GetBuiltinPrompts']();
}

export function GetClaudeHooks() {
  return window['go']['main']['App']['GetClaudeHooks']();
}

export function GetConfigDir() {
  return window['go']['main']['App']['GetConfigDir']();
}

export function GetContextFile(arg1, arg2) {
  return window['go']['main']['App']['GetContextFile'](arg1, arg2);
}

export function GetDefaultClaudeConfig() {
  return window['go']['main']['App']['GetDefaultClaudeConfig']();
}

export function GetDefaultCodexConfig() {
  return window['go']['main']['App']['GetDefaultCodexConfig']();
}

export function GetDefaultGeminiConfig() {
  return window['go']['main']['App']['GetDefaultGeminiConfig']();
}

export function GetDefaultNullClawConfig() {
  return window['go']['main']['App']['GetDefaultNullClawConfig']();
}

export function GetDefaultPicoClawConfig() {
  return window['go']['main']['App']['GetDefaultPicoClawConfig']();
}

export function GetProxySettings() {
  return window['go']['main']['App']['GetProxySettings']();
}

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}

export function GetToolConfigPath(arg1) {
  return window['go']['main']['App']['GetToolConfigPath'](arg1);
}

export function GetToolOutput(arg1, arg2) {
  return window['go']['main']['App']['GetToolOutput'](arg1, arg2);
}

export function GetUsageReport(arg1) {
  return window['go']['main']['App']['GetUsageReport'](arg1);
}

export function ImportPrompts() {
  return window['go']['main']['App']['ImportPrompts']();
}

export function InstallAllTools() {
  return window['go']['main']['App']['InstallAllTools']();
}

export function InstallBun() {
  return window['go']['main']['App']['InstallBun']();
}

export function InstallTool(arg1) {
  return window['go']['main']['App']['InstallTool'](arg1);
}

export function KillCLIProcess(arg1) {
  return window['go']['main']['App']['KillCLIProcess'](arg1);
}

export function LaunchTool(arg1, arg2) {
  return window['go']['main']['App']['LaunchTool'](arg1, arg2);
}

export function ListAllAPIKeys() {
  return window['go']['main']['App']['ListAllAPIKeys']();
}

export function ListCLIProcesses() {
  return window['go']['main']['App']['ListCLIProcesses']();
}

export function ListClaudeConfigs() {
  return window['go']['main']['App']['ListClaudeConfigs']();
}

export function ListCodexConfigs() {
  return window['go']['main']['App']['ListCodexConfigs']();
}

export function ListConfigSnapshots(arg1) {
  return window['go']['main']['App']['ListConfigSnapshots'](arg1);
}

export function ListGeminiConfigs() {
  return window['go']['main']['App']['ListGeminiConfigs']();
}

export function ListMCPPresets() {
  return window['go']['main']['App']['ListMCPPresets']();
}

export function ListNullClawConfigs() {
  return window['go']['main']['App']['ListNullClawConfigs']();
}

export function ListPicoClawConfigs() {
  return window['go']['main']['App']['ListPicoClawConfigs']();
}

export function ListPrompts(arg1) {
  return window['go']['main']['App']['ListPrompts'](arg1);
}

export function LoadClaudeConfig(arg1) {
  return window['go']['main']['App']['LoadClaudeConfig'](arg1);
}

export function LoadCodexConfig(arg1) {
  return window['go']['main']['App']['LoadCodexConfig'](arg1);
}

export function LoadGeminiConfig(arg1) {
  return window['go']['main']['App']['LoadGeminiConfig'](arg1);
}

export function LoadNullClawConfig(arg1) {
  return window['go']['main']['App']['LoadNullClawConfig'](arg1);
}

export function LoadPicoClawConfig(arg1) {
  return window['go']['main']['App']['LoadPicoClawConfig'](arg1);
}

export function OpenAdminPanel() {
  return window['go']['main']['App']['OpenAdminPanel']();
}

export function OpenConfigDir() {
  return window['go']['main']['App']['OpenConfigDir']();
}

export function OpenFolderAndScanContext() {
  return window['go']['main']['App']['OpenFolderAndScanContext']();
}

export function OpenToolConfigDir(arg1) {
  return window['go']['main']['App']['OpenToolConfigDir'](arg1);
}

export function PackageClaudeConfig(arg1) {
  return window['go']['main']['App']['PackageClaudeConfig'](arg1);
}

export function PingLurusAPI() {
  return window['go']['main']['App']['PingLurusAPI']();
}

export function ReadToolConfig(arg1) {
  return window['go']['main']['App']['ReadToolConfig'](arg1);
}

export function RestoreConfigSnapshot(arg1, arg2) {
  return window['go']['main']['App']['RestoreConfigSnapshot'](arg1, arg2);
}

export function SaveAppSettings(arg1) {
  return window['go']['main']['App']['SaveAppSettings'](arg1);
}

export function SaveClaudeConfig(arg1, arg2) {
  return window['go']['main']['App']['SaveClaudeConfig'](arg1, arg2);
}

export function SaveClaudeHooks(arg1) {
  return window['go']['main']['App']['SaveClaudeHooks'](arg1);
}

export function SaveCodexConfig(arg1, arg2) {
  return window['go']['main']['App']['SaveCodexConfig'](arg1, arg2);
}

export function SaveContextFile(arg1) {
  return window['go']['main']['App']['SaveContextFile'](arg1);
}

export function SaveGeminiConfig(arg1, arg2) {
  return window['go']['main']['App']['SaveGeminiConfig'](arg1, arg2);
}

export function SaveMCPPreset(arg1) {
  return window['go']['main']['App']['SaveMCPPreset'](arg1);
}

export function SaveNullClawConfig(arg1, arg2) {
  return window['go']['main']['App']['SaveNullClawConfig'](arg1, arg2);
}

export function SavePicoClawConfig(arg1, arg2) {
  return window['go']['main']['App']['SavePicoClawConfig'](arg1, arg2);
}

export function SavePrompt(arg1) {
  return window['go']['main']['App']['SavePrompt'](arg1);
}

export function SaveProxySettings(arg1) {
  return window['go']['main']['App']['SaveProxySettings'](arg1);
}

export function SaveToolConfig(arg1, arg2) {
  return window['go']['main']['App']['SaveToolConfig'](arg1, arg2);
}

export function StopToolSession(arg1) {
  return window['go']['main']['App']['StopToolSession'](arg1);
}

export function TakeConfigSnapshot(arg1, arg2) {
  return window['go']['main']['App']['TakeConfigSnapshot'](arg1, arg2);
}

export function UninstallAllTools() {
  return window['go']['main']['App']['UninstallAllTools']();
}

export function UninstallTool(arg1) {
  return window['go']['main']['App']['UninstallTool'](arg1);
}

export function UpdateAPIKey(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateAPIKey'](arg1, arg2, arg3);
}

export function UpdateAllTools() {
  return window['go']['main']['App']['UpdateAllTools']();
}

export function UpdateTool(arg1) {
  return window['go']['main']['App']['UpdateTool'](arg1);
}

export function ValidateClaudeConfig(arg1) {
  return window['go']['main']['App']['ValidateClaudeConfig'](arg1);
}

export function ValidateCodexConfig(arg1) {
  return window['go']['main']['App']['ValidateCodexConfig'](arg1);
}

export function ValidateGeminiConfig(arg1) {
  return window['go']['main']['App']['ValidateGeminiConfig'](arg1);
}

export function ValidateNullClawConfig(arg1) {
  return window['go']['main']['App']['ValidateNullClawConfig'](arg1);
}

export function ValidatePicoClawConfig(arg1) {
  return window['go']['main']['App']['ValidatePicoClawConfig'](arg1);
}
