// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {preset} from '../models';
import {mcp} from '../models';
import {billing} from '../models';
import {toolhealth} from '../models';
import {updater} from '../models';
import {installer} from '../models';
import {proxydetect} from '../models';
import {config} from '../models';
import {appconfig} from '../models';
import {promptlib} from '../models';
import {docmgr} from '../models';
import {proxy} from '../models';
import {main} from '../models';
import {analytics} from '../models';
import {envmgr} from '../models';
import {process} from '../models';
import {snapshot} from '../models';
import {toolconfig} from '../models';
import {validator} from '../models';

export function ApplyMCPServerToTool(arg1:string,arg2:mcp.MCPServer):Promise<void>;

export function ApplySelfUpdate():Promise<void>;

export function BillingCancelSubscription(arg1:number):Promise<void>;

export function BillingCreateTopUp(arg1:number,arg2:string):Promise<billing.PaymentResult>;

export function BillingGetPlans():Promise<Array<billing.SubscriptionPlan>>;

export function BillingGetQuotaSummary():Promise<billing.QuotaSummary>;

export function BillingGetSubscriptions():Promise<Array<billing.SubscriptionInfo>>;

export function BillingGetTopUpInfo():Promise<billing.TopUpInfo>;

export function BillingGetUserInfo():Promise<billing.UserInfo>;

export function BillingOpenPaymentURL(arg1:string):Promise<void>;

export function BillingRedeemCode(arg1:string):Promise<number>;

export function BillingSubscribe(arg1:string,arg2:string):Promise<billing.PaymentResult>;

export function CheckAllToolHealth():Promise<Record<string, toolhealth.HealthResult>>;

export function CheckAllUpdates():Promise<Record<string, updater.UpdateInfo>>;

export function CheckBunInstalled():Promise<boolean>;

export function CheckNodeInstalled():Promise<boolean>;

export function CheckSelfUpdate():Promise<updater.UpdateInfo>;

export function CheckToolHealth(arg1:string):Promise<toolhealth.HealthResult>;

export function ApplyClaudePreset(arg1:string):Promise<config.ClaudeConfig>;

export function ApplyCodexPreset(arg1:string):Promise<config.CodexConfig>;

export function ApplyGeminiPreset(arg1:string):Promise<config.GeminiConfig>;

export function ClearAllSnapshots():Promise<number>;

export function ClearToolSnapshots(arg1:string):Promise<number>;

export function ClearAllUserPrompts():Promise<number>;

export function ConfigureAllProxy():Promise<Record<string, string>>;

export function DeleteClaudeConfig(arg1:string):Promise<void>;

export function DeleteCodexConfig(arg1:string):Promise<void>;

export function DeleteConfigSnapshot(arg1:string,arg2:string):Promise<void>;

export function DeleteGeminiConfig(arg1:string):Promise<void>;

export function DeleteMCPPreset(arg1:string):Promise<void>;

export function DeleteNullClawConfig(arg1:string):Promise<void>;

export function DeletePicoClawConfig(arg1:string):Promise<void>;

export function DeletePrompt(arg1:string):Promise<void>;

export function DetectAllTools():Promise<Record<string, installer.ToolStatus>>;

export function DetectSystemProxy():Promise<Array<proxydetect.DetectedProxy>>;

export function DiffConfigSnapshots(arg1:string,arg2:string,arg3:string):Promise<string>;

export function DownloadCodexBinary(arg1:string):Promise<string>;

export function ExportClaudeConfig(arg1:config.ClaudeConfig):Promise<string>;

export function ExportCodexConfig(arg1:config.CodexConfig):Promise<string>;

export function ExportGeminiConfig(arg1:config.GeminiConfig):Promise<Array<string>>;

export function ExportNullClawConfig(arg1:config.NullClawConfig):Promise<string>;

export function ExportPicoClawConfig(arg1:config.PicoClawConfig):Promise<string>;

export function ExportPrompts():Promise<string>;

export function GenerateClaudeConfig(arg1:config.ClaudeConfig):Promise<string>;

export function GenerateCodexConfig(arg1:config.CodexConfig):Promise<string>;

export function GenerateGeminiConfig(arg1:config.GeminiConfig):Promise<string>;

export function GenerateNullClawConfig(arg1:config.NullClawConfig):Promise<string>;

export function GeneratePicoClawConfig(arg1:config.PicoClawConfig):Promise<string>;

export function GetAllToolConfigPaths():Promise<Record<string, string>>;

export function GetAppSettings():Promise<appconfig.AppSettings>;

export function GetAppVersion():Promise<string>;

export function GetBuiltinMCPPresets():Promise<Array<mcp.MCPPreset>>;

export function GetClaudePresets():Promise<Array<preset.Preset>>;

export function GetCodexPresets():Promise<Array<preset.Preset>>;

export function GetGeminiPresets():Promise<Array<preset.Preset>>;

export function GetBuiltinPrompts():Promise<Array<promptlib.Prompt>>;

export function GetClaudeHooks():Promise<Record<string, any>>;

export function GetConfigDir():Promise<string>;

export function GetContextFile(arg1:string,arg2:string):Promise<docmgr.ContextFile>;

export function GetDefaultClaudeConfig():Promise<config.ClaudeConfig>;

export function GetDefaultCodexConfig():Promise<config.CodexConfig>;

export function GetDefaultGeminiConfig():Promise<config.GeminiConfig>;

export function GetDefaultNullClawConfig():Promise<config.NullClawConfig>;

export function GetDefaultPicoClawConfig():Promise<config.PicoClawConfig>;

export function GetProxySettings():Promise<proxy.ProxySettings>;

export function GetSystemInfo():Promise<main.SystemInfo>;

export function GetToolConfigPath(arg1:string):Promise<string>;

export function GetToolOutput(arg1:string,arg2:number):Promise<Array<string>>;

export function GetUsageReport(arg1:number):Promise<analytics.UsageReport>;

export function ImportPrompts():Promise<number>;

export function InstallAllTools():Promise<Array<installer.InstallResult>>;

export function InstallBun():Promise<string>;

export function InstallTool(arg1:string):Promise<installer.InstallResult>;

export function KillCLIProcess(arg1:number):Promise<void>;

export function LaunchTool(arg1:string,arg2:Array<string>):Promise<string>;

export function ListAllAPIKeys():Promise<Array<envmgr.KeyEntry>>;

export function ListCLIProcesses():Promise<Array<process.ProcessInfo>>;

export function ListClaudeConfigs():Promise<Array<string>>;

export function ListCodexConfigs():Promise<Array<string>>;

export function ListConfigSnapshots(arg1:string):Promise<Array<snapshot.SnapshotMeta>>;

export function ListGeminiConfigs():Promise<Array<string>>;

export function ListMCPPresets():Promise<Array<mcp.MCPPreset>>;

export function ListNullClawConfigs():Promise<Array<string>>;

export function ListPicoClawConfigs():Promise<Array<string>>;

export function ListPrompts(arg1:string):Promise<Array<promptlib.Prompt>>;

export function LoadClaudeConfig(arg1:string):Promise<config.ClaudeConfig>;

export function LoadCodexConfig(arg1:string):Promise<config.CodexConfig>;

export function LoadGeminiConfig(arg1:string):Promise<config.GeminiConfig>;

export function LoadNullClawConfig(arg1:string):Promise<config.NullClawConfig>;

export function LoadPicoClawConfig(arg1:string):Promise<config.PicoClawConfig>;

export function OpenAdminPanel():Promise<void>;

export function OpenConfigDir():Promise<void>;

export function OpenFolderAndScanContext():Promise<Array<docmgr.ContextFile>>;

export function OpenToolConfigDir(arg1:string):Promise<void>;

export function PackageClaudeConfig(arg1:config.ClaudeConfig):Promise<string>;

export function PingLurusAPI():Promise<boolean>;

export function ReadToolConfig(arg1:string):Promise<toolconfig.ToolConfigInfo>;

export function RestoreConfigSnapshot(arg1:string,arg2:string):Promise<void>;

export function SaveAppSettings(arg1:appconfig.AppSettings):Promise<void>;

export function SaveClaudeConfig(arg1:string,arg2:config.ClaudeConfig):Promise<void>;

export function SaveClaudeHooks(arg1:Record<string, any>):Promise<void>;

export function SaveCodexConfig(arg1:string,arg2:config.CodexConfig):Promise<void>;

export function SaveContextFile(arg1:docmgr.ContextFile):Promise<void>;

export function SaveGeminiConfig(arg1:string,arg2:config.GeminiConfig):Promise<void>;

export function SaveMCPPreset(arg1:mcp.MCPPreset):Promise<void>;

export function SaveNullClawConfig(arg1:string,arg2:config.NullClawConfig):Promise<void>;

export function SavePicoClawConfig(arg1:string,arg2:config.PicoClawConfig):Promise<void>;

export function SavePrompt(arg1:promptlib.Prompt):Promise<void>;

export function SaveProxySettings(arg1:proxy.ProxySettings):Promise<void>;

export function SaveToolConfig(arg1:string,arg2:string):Promise<void>;

export function StopToolSession(arg1:string):Promise<void>;

export function TakeConfigSnapshot(arg1:string,arg2:string):Promise<void>;

export function UninstallAllTools():Promise<Array<installer.InstallResult>>;

export function UninstallTool(arg1:string):Promise<installer.InstallResult>;

export function UpdateAPIKey(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UpdateAllTools():Promise<Array<installer.InstallResult>>;

export function UpdateTool(arg1:string):Promise<installer.InstallResult>;

export function ValidateClaudeConfig(arg1:config.ClaudeConfig):Promise<validator.ValidationResult>;

export function ValidateCodexConfig(arg1:config.CodexConfig):Promise<validator.ValidationResult>;

export function ValidateGeminiConfig(arg1:config.GeminiConfig):Promise<validator.ValidationResult>;

export function ValidateNullClawConfig(arg1:config.NullClawConfig):Promise<validator.ValidationResult>;

export function ValidatePicoClawConfig(arg1:config.PicoClawConfig):Promise<validator.ValidationResult>;
