// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyAllToolRelays() {
  return window['go']['main']['App']['ApplyAllToolRelays']();
}

export function ApplyClaudePreset(arg1) {
  return window['go']['main']['App']['ApplyClaudePreset'](arg1);
}

export function ApplyCodexPreset(arg1) {
  return window['go']['main']['App']['ApplyCodexPreset'](arg1);
}

export function ApplyGeminiPreset(arg1) {
  return window['go']['main']['App']['ApplyGeminiPreset'](arg1);
}

export function ApplyMCPServerToTool(arg1, arg2) {
  return window['go']['main']['App']['ApplyMCPServerToTool'](arg1, arg2);
}

export function ApplySelfUpdate() {
  return window['go']['main']['App']['ApplySelfUpdate']();
}

export function AutoConfigureToolForGateway(arg1) {
  return window['go']['main']['App']['AutoConfigureToolForGateway'](arg1);
}

export function AutoConfigureToolsForGateway() {
  return window['go']['main']['App']['AutoConfigureToolsForGateway']();
}

export function AutoFixToolConfig(arg1) {
  return window['go']['main']['App']['AutoFixToolConfig'](arg1);
}

export function BillingCancelSubscription(arg1) {
  return window['go']['main']['App']['BillingCancelSubscription'](arg1);
}

export function BillingCreateTopUp(arg1, arg2) {
  return window['go']['main']['App']['BillingCreateTopUp'](arg1, arg2);
}

export function BillingGetIdentityOverview(arg1) {
  return window['go']['main']['App']['BillingGetIdentityOverview'](arg1);
}

export function BillingGetPlans() {
  return window['go']['main']['App']['BillingGetPlans']();
}

export function BillingGetQuotaSummary() {
  return window['go']['main']['App']['BillingGetQuotaSummary']();
}

export function BillingGetSubscriptions() {
  return window['go']['main']['App']['BillingGetSubscriptions']();
}

export function BillingGetTopUpInfo() {
  return window['go']['main']['App']['BillingGetTopUpInfo']();
}

export function BillingGetUserInfo() {
  return window['go']['main']['App']['BillingGetUserInfo']();
}

export function BillingOpenPaymentURL(arg1) {
  return window['go']['main']['App']['BillingOpenPaymentURL'](arg1);
}

export function BillingOpenTopup(arg1) {
  return window['go']['main']['App']['BillingOpenTopup'](arg1);
}

export function BillingRedeemCode(arg1) {
  return window['go']['main']['App']['BillingRedeemCode'](arg1);
}

export function BillingSubscribe(arg1, arg2) {
  return window['go']['main']['App']['BillingSubscribe'](arg1, arg2);
}

export function BillingValidateToken(arg1, arg2) {
  return window['go']['main']['App']['BillingValidateToken'](arg1, arg2);
}

export function CheckAllToolHealth() {
  return window['go']['main']['App']['CheckAllToolHealth']();
}

export function CheckAllUpdates() {
  return window['go']['main']['App']['CheckAllUpdates']();
}

export function CheckBunInstalled() {
  return window['go']['main']['App']['CheckBunInstalled']();
}

export function CheckDependencies() {
  return window['go']['main']['App']['CheckDependencies']();
}

export function CheckGYStatus() {
  return window['go']['main']['App']['CheckGYStatus']();
}

export function CheckNodeInstalled() {
  return window['go']['main']['App']['CheckNodeInstalled']();
}

export function CheckRelayHealth() {
  return window['go']['main']['App']['CheckRelayHealth']();
}

export function CheckSelfUpdate() {
  return window['go']['main']['App']['CheckSelfUpdate']();
}

export function CheckToolHealth(arg1) {
  return window['go']['main']['App']['CheckToolHealth'](arg1);
}

export function ClearAllSnapshots() {
  return window['go']['main']['App']['ClearAllSnapshots']();
}

export function ClearAllUserPrompts() {
  return window['go']['main']['App']['ClearAllUserPrompts']();
}

export function ClearToolSnapshots(arg1) {
  return window['go']['main']['App']['ClearToolSnapshots'](arg1);
}

export function ConfigureAllProxy() {
  return window['go']['main']['App']['ConfigureAllProxy']();
}

export function ConfigureAllToolsRelay() {
  return window['go']['main']['App']['ConfigureAllToolsRelay']();
}

export function DeleteApp(arg1) {
  return window['go']['main']['App']['DeleteApp'](arg1);
}

export function DeleteClaudeConfig(arg1) {
  return window['go']['main']['App']['DeleteClaudeConfig'](arg1);
}

export function DeleteCodexConfig(arg1) {
  return window['go']['main']['App']['DeleteCodexConfig'](arg1);
}

export function DeleteConfigSnapshot(arg1, arg2) {
  return window['go']['main']['App']['DeleteConfigSnapshot'](arg1, arg2);
}

export function DeleteGeminiConfig(arg1) {
  return window['go']['main']['App']['DeleteGeminiConfig'](arg1);
}

export function DeleteMCPPreset(arg1) {
  return window['go']['main']['App']['DeleteMCPPreset'](arg1);
}

export function DeleteNullClawConfig(arg1) {
  return window['go']['main']['App']['DeleteNullClawConfig'](arg1);
}

export function DeleteOpenClawConfig(arg1) {
  return window['go']['main']['App']['DeleteOpenClawConfig'](arg1);
}

export function DeletePicoClawConfig(arg1) {
  return window['go']['main']['App']['DeletePicoClawConfig'](arg1);
}

export function DeletePrompt(arg1) {
  return window['go']['main']['App']['DeletePrompt'](arg1);
}

export function DeleteRelayEndpoint(arg1) {
  return window['go']['main']['App']['DeleteRelayEndpoint'](arg1);
}

export function DeleteZeroClawConfig(arg1) {
  return window['go']['main']['App']['DeleteZeroClawConfig'](arg1);
}

export function DetectAllTools() {
  return window['go']['main']['App']['DetectAllTools']();
}

export function DetectSystemProxy() {
  return window['go']['main']['App']['DetectSystemProxy']();
}

export function DiffConfigSnapshots(arg1, arg2, arg3) {
  return window['go']['main']['App']['DiffConfigSnapshots'](arg1, arg2, arg3);
}

export function DisconnectAllToolsFromGateway() {
  return window['go']['main']['App']['DisconnectAllToolsFromGateway']();
}

export function DisconnectToolFromGateway(arg1) {
  return window['go']['main']['App']['DisconnectToolFromGateway'](arg1);
}

export function DownloadCodexBinary(arg1) {
  return window['go']['main']['App']['DownloadCodexBinary'](arg1);
}

export function DownloadCreator() {
  return window['go']['main']['App']['DownloadCreator']();
}

export function EnsureServerBinary() {
  return window['go']['main']['App']['EnsureServerBinary']();
}

export function ExportClaudeConfig(arg1) {
  return window['go']['main']['App']['ExportClaudeConfig'](arg1);
}

export function ExportCodexConfig(arg1) {
  return window['go']['main']['App']['ExportCodexConfig'](arg1);
}

export function ExportDiagnostics() {
  return window['go']['main']['App']['ExportDiagnostics']();
}

export function ExportGeminiConfig(arg1) {
  return window['go']['main']['App']['ExportGeminiConfig'](arg1);
}

export function ExportNullClawConfig(arg1) {
  return window['go']['main']['App']['ExportNullClawConfig'](arg1);
}

export function ExportOpenClawConfig(arg1) {
  return window['go']['main']['App']['ExportOpenClawConfig'](arg1);
}

export function ExportPicoClawConfig(arg1) {
  return window['go']['main']['App']['ExportPicoClawConfig'](arg1);
}

export function ExportPrompts() {
  return window['go']['main']['App']['ExportPrompts']();
}

export function ExportZeroClawConfig(arg1) {
  return window['go']['main']['App']['ExportZeroClawConfig'](arg1);
}

export function FetchCloudPresets(arg1) {
  return window['go']['main']['App']['FetchCloudPresets'](arg1);
}

export function FetchCloudRelayEndpoints() {
  return window['go']['main']['App']['FetchCloudRelayEndpoints']();
}

export function FetchModelCatalog() {
  return window['go']['main']['App']['FetchModelCatalog']();
}

export function FullSetupForGateway() {
  return window['go']['main']['App']['FullSetupForGateway']();
}

export function GenerateClaudeConfig(arg1) {
  return window['go']['main']['App']['GenerateClaudeConfig'](arg1);
}

export function GenerateCodexConfig(arg1) {
  return window['go']['main']['App']['GenerateCodexConfig'](arg1);
}

export function GenerateGeminiConfig(arg1) {
  return window['go']['main']['App']['GenerateGeminiConfig'](arg1);
}

export function GenerateNullClawConfig(arg1) {
  return window['go']['main']['App']['GenerateNullClawConfig'](arg1);
}

export function GenerateOpenClawConfig(arg1) {
  return window['go']['main']['App']['GenerateOpenClawConfig'](arg1);
}

export function GeneratePicoClawConfig(arg1) {
  return window['go']['main']['App']['GeneratePicoClawConfig'](arg1);
}

export function GenerateZeroClawConfig(arg1) {
  return window['go']['main']['App']['GenerateZeroClawConfig'](arg1);
}

export function GetAllToolConfigPaths() {
  return window['go']['main']['App']['GetAllToolConfigPaths']();
}

export function GetAppSettings() {
  return window['go']['main']['App']['GetAppSettings']();
}

export function GetAppSummaries(arg1) {
  return window['go']['main']['App']['GetAppSummaries'](arg1);
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetBuiltinMCPPresets() {
  return window['go']['main']['App']['GetBuiltinMCPPresets']();
}

export function GetBuiltinPrompts() {
  return window['go']['main']['App']['GetBuiltinPrompts']();
}

export function GetClaudeHooks() {
  return window['go']['main']['App']['GetClaudeHooks']();
}

export function GetClaudePresets() {
  return window['go']['main']['App']['GetClaudePresets']();
}

export function GetCodexPresets() {
  return window['go']['main']['App']['GetCodexPresets']();
}

export function GetConfigDir() {
  return window['go']['main']['App']['GetConfigDir']();
}

export function GetConnectedAppCount() {
  return window['go']['main']['App']['GetConnectedAppCount']();
}

export function GetContextFile(arg1, arg2) {
  return window['go']['main']['App']['GetContextFile'](arg1, arg2);
}

export function GetDaySummaries(arg1) {
  return window['go']['main']['App']['GetDaySummaries'](arg1);
}

export function GetDefaultClaudeConfig() {
  return window['go']['main']['App']['GetDefaultClaudeConfig']();
}

export function GetDefaultCodexConfig() {
  return window['go']['main']['App']['GetDefaultCodexConfig']();
}

export function GetDefaultGeminiConfig() {
  return window['go']['main']['App']['GetDefaultGeminiConfig']();
}

export function GetDefaultNullClawConfig() {
  return window['go']['main']['App']['GetDefaultNullClawConfig']();
}

export function GetDefaultOpenClawConfig() {
  return window['go']['main']['App']['GetDefaultOpenClawConfig']();
}

export function GetDefaultPicoClawConfig() {
  return window['go']['main']['App']['GetDefaultPicoClawConfig']();
}

export function GetDefaultZeroClawConfig() {
  return window['go']['main']['App']['GetDefaultZeroClawConfig']();
}

export function GetGYProducts() {
  return window['go']['main']['App']['GetGYProducts']();
}

export function GetGatewayConfig() {
  return window['go']['main']['App']['GetGatewayConfig']();
}

export function GetGatewayStatus() {
  return window['go']['main']['App']['GetGatewayStatus']();
}

export function GetGatewayURL() {
  return window['go']['main']['App']['GetGatewayURL']();
}

export function GetGeminiPresets() {
  return window['go']['main']['App']['GetGeminiPresets']();
}

export function GetModelSummaries(arg1) {
  return window['go']['main']['App']['GetModelSummaries'](arg1);
}

export function GetProxySettings() {
  return window['go']['main']['App']['GetProxySettings']();
}

export function GetRecentActivity(arg1) {
  return window['go']['main']['App']['GetRecentActivity'](arg1);
}

export function GetRecommendedConfig(arg1) {
  return window['go']['main']['App']['GetRecommendedConfig'](arg1);
}

export function GetRegisteredApp(arg1) {
  return window['go']['main']['App']['GetRegisteredApp'](arg1);
}

export function GetRegisteredApps() {
  return window['go']['main']['App']['GetRegisteredApps']();
}

export function GetRelayEndpoints() {
  return window['go']['main']['App']['GetRelayEndpoints']();
}

export function GetRequestLog(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetRequestLog'](arg1, arg2, arg3);
}

export function GetServerAdminToken() {
  return window['go']['main']['App']['GetServerAdminToken']();
}

export function GetServerConfig() {
  return window['go']['main']['App']['GetServerConfig']();
}

export function GetServerStatus() {
  return window['go']['main']['App']['GetServerStatus']();
}

export function GetServerURL() {
  return window['go']['main']['App']['GetServerURL']();
}

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}

export function GetTodaySummary() {
  return window['go']['main']['App']['GetTodaySummary']();
}

export function GetToolConfigPath(arg1) {
  return window['go']['main']['App']['GetToolConfigPath'](arg1);
}

export function GetToolDownloadManifest() {
  return window['go']['main']['App']['GetToolDownloadManifest']();
}

export function GetToolOutput(arg1, arg2) {
  return window['go']['main']['App']['GetToolOutput'](arg1, arg2);
}

export function GetToolRelayMapping() {
  return window['go']['main']['App']['GetToolRelayMapping']();
}

export function GetUsageInsights(arg1) {
  return window['go']['main']['App']['GetUsageInsights'](arg1);
}

export function GetUsageReport(arg1) {
  return window['go']['main']['App']['GetUsageReport'](arg1);
}

export function ImportPrompts() {
  return window['go']['main']['App']['ImportPrompts']();
}

export function InstallAllTools() {
  return window['go']['main']['App']['InstallAllTools']();
}

export function InstallBun() {
  return window['go']['main']['App']['InstallBun']();
}

export function InstallDependency(arg1) {
  return window['go']['main']['App']['InstallDependency'](arg1);
}

export function InstallTool(arg1) {
  return window['go']['main']['App']['InstallTool'](arg1);
}

export function KillCLIProcess(arg1) {
  return window['go']['main']['App']['KillCLIProcess'](arg1);
}

export function LaunchGYProduct(arg1) {
  return window['go']['main']['App']['LaunchGYProduct'](arg1);
}

export function LaunchTool(arg1, arg2) {
  return window['go']['main']['App']['LaunchTool'](arg1, arg2);
}

export function ListAllAPIKeys() {
  return window['go']['main']['App']['ListAllAPIKeys']();
}

export function ListCLIProcesses() {
  return window['go']['main']['App']['ListCLIProcesses']();
}

export function ListClaudeConfigs() {
  return window['go']['main']['App']['ListClaudeConfigs']();
}

export function ListCodexConfigs() {
  return window['go']['main']['App']['ListCodexConfigs']();
}

export function ListConfigSnapshots(arg1) {
  return window['go']['main']['App']['ListConfigSnapshots'](arg1);
}

export function ListGeminiConfigs() {
  return window['go']['main']['App']['ListGeminiConfigs']();
}

export function ListMCPPresets() {
  return window['go']['main']['App']['ListMCPPresets']();
}

export function ListNullClawConfigs() {
  return window['go']['main']['App']['ListNullClawConfigs']();
}

export function ListOpenClawConfigs() {
  return window['go']['main']['App']['ListOpenClawConfigs']();
}

export function ListPicoClawConfigs() {
  return window['go']['main']['App']['ListPicoClawConfigs']();
}

export function ListPrompts(arg1) {
  return window['go']['main']['App']['ListPrompts'](arg1);
}

export function ListToolSnapshots(arg1) {
  return window['go']['main']['App']['ListToolSnapshots'](arg1);
}

export function ListZeroClawConfigs() {
  return window['go']['main']['App']['ListZeroClawConfigs']();
}

export function LoadClaudeConfig(arg1) {
  return window['go']['main']['App']['LoadClaudeConfig'](arg1);
}

export function LoadCodexConfig(arg1) {
  return window['go']['main']['App']['LoadCodexConfig'](arg1);
}

export function LoadGeminiConfig(arg1) {
  return window['go']['main']['App']['LoadGeminiConfig'](arg1);
}

export function LoadNullClawConfig(arg1) {
  return window['go']['main']['App']['LoadNullClawConfig'](arg1);
}

export function LoadOpenClawConfig(arg1) {
  return window['go']['main']['App']['LoadOpenClawConfig'](arg1);
}

export function LoadPicoClawConfig(arg1) {
  return window['go']['main']['App']['LoadPicoClawConfig'](arg1);
}

export function LoadZeroClawConfig(arg1) {
  return window['go']['main']['App']['LoadZeroClawConfig'](arg1);
}

export function OpenAdminPanel() {
  return window['go']['main']['App']['OpenAdminPanel']();
}

export function OpenConfigDir() {
  return window['go']['main']['App']['OpenConfigDir']();
}

export function OpenFolderAndScanContext() {
  return window['go']['main']['App']['OpenFolderAndScanContext']();
}

export function OpenServerAdminPanel() {
  return window['go']['main']['App']['OpenServerAdminPanel']();
}

export function OpenToolConfigDir(arg1) {
  return window['go']['main']['App']['OpenToolConfigDir'](arg1);
}

export function PackageClaudeConfig(arg1) {
  return window['go']['main']['App']['PackageClaudeConfig'](arg1);
}

export function PingEndpoint(arg1) {
  return window['go']['main']['App']['PingEndpoint'](arg1);
}

export function PingGatewayUpstream() {
  return window['go']['main']['App']['PingGatewayUpstream']();
}

export function PingLurusAPI() {
  return window['go']['main']['App']['PingLurusAPI']();
}

export function PromoterGetInfo() {
  return window['go']['main']['App']['PromoterGetInfo']();
}

export function PromoterGetShareLink() {
  return window['go']['main']['App']['PromoterGetShareLink']();
}

export function QuickSetup(arg1) {
  return window['go']['main']['App']['QuickSetup'](arg1);
}

export function ReadToolConfig(arg1) {
  return window['go']['main']['App']['ReadToolConfig'](arg1);
}

export function RegisterApp(arg1, arg2, arg3) {
  return window['go']['main']['App']['RegisterApp'](arg1, arg2, arg3);
}

export function ResetAppToken(arg1) {
  return window['go']['main']['App']['ResetAppToken'](arg1);
}

export function RestoreConfigSnapshot(arg1, arg2) {
  return window['go']['main']['App']['RestoreConfigSnapshot'](arg1, arg2);
}

export function RestoreToolSnapshot(arg1, arg2) {
  return window['go']['main']['App']['RestoreToolSnapshot'](arg1, arg2);
}

export function RunEnvironmentCheck() {
  return window['go']['main']['App']['RunEnvironmentCheck']();
}

export function SaveAppSettings(arg1) {
  return window['go']['main']['App']['SaveAppSettings'](arg1);
}

export function SaveClaudeConfig(arg1, arg2) {
  return window['go']['main']['App']['SaveClaudeConfig'](arg1, arg2);
}

export function SaveClaudeHooks(arg1) {
  return window['go']['main']['App']['SaveClaudeHooks'](arg1);
}

export function SaveCodexConfig(arg1, arg2) {
  return window['go']['main']['App']['SaveCodexConfig'](arg1, arg2);
}

export function SaveContextFile(arg1) {
  return window['go']['main']['App']['SaveContextFile'](arg1);
}

export function SaveGatewayConfig(arg1) {
  return window['go']['main']['App']['SaveGatewayConfig'](arg1);
}

export function SaveGeminiConfig(arg1, arg2) {
  return window['go']['main']['App']['SaveGeminiConfig'](arg1, arg2);
}

export function SaveMCPPreset(arg1) {
  return window['go']['main']['App']['SaveMCPPreset'](arg1);
}

export function SaveNullClawConfig(arg1, arg2) {
  return window['go']['main']['App']['SaveNullClawConfig'](arg1, arg2);
}

export function SaveOpenClawConfig(arg1, arg2) {
  return window['go']['main']['App']['SaveOpenClawConfig'](arg1, arg2);
}

export function SavePicoClawConfig(arg1, arg2) {
  return window['go']['main']['App']['SavePicoClawConfig'](arg1, arg2);
}

export function SavePrompt(arg1) {
  return window['go']['main']['App']['SavePrompt'](arg1);
}

export function SaveProxySettings(arg1) {
  return window['go']['main']['App']['SaveProxySettings'](arg1);
}

export function SaveRelayEndpoint(arg1) {
  return window['go']['main']['App']['SaveRelayEndpoint'](arg1);
}

export function SaveServerConfig(arg1) {
  return window['go']['main']['App']['SaveServerConfig'](arg1);
}

export function SaveToolConfig(arg1, arg2) {
  return window['go']['main']['App']['SaveToolConfig'](arg1, arg2);
}

export function SaveToolRelayMapping(arg1) {
  return window['go']['main']['App']['SaveToolRelayMapping'](arg1);
}

export function SaveZeroClawConfig(arg1, arg2) {
  return window['go']['main']['App']['SaveZeroClawConfig'](arg1, arg2);
}

export function SetAppConnected(arg1, arg2) {
  return window['go']['main']['App']['SetAppConnected'](arg1, arg2);
}

export function StartGateway() {
  return window['go']['main']['App']['StartGateway']();
}

export function StartServer() {
  return window['go']['main']['App']['StartServer']();
}

export function StopGateway() {
  return window['go']['main']['App']['StopGateway']();
}

export function StopServer() {
  return window['go']['main']['App']['StopServer']();
}

export function StopToolSession(arg1) {
  return window['go']['main']['App']['StopToolSession'](arg1);
}

export function SwitchModel(arg1) {
  return window['go']['main']['App']['SwitchModel'](arg1);
}

export function SyncToolConnectionStatus() {
  return window['go']['main']['App']['SyncToolConnectionStatus']();
}

export function TakeConfigSnapshot(arg1, arg2) {
  return window['go']['main']['App']['TakeConfigSnapshot'](arg1, arg2);
}

export function UninstallAllTools() {
  return window['go']['main']['App']['UninstallAllTools']();
}

export function UninstallTool(arg1) {
  return window['go']['main']['App']['UninstallTool'](arg1);
}

export function UpdateAPIKey(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateAPIKey'](arg1, arg2, arg3);
}

export function UpdateAllTools() {
  return window['go']['main']['App']['UpdateAllTools']();
}

export function UpdateTool(arg1) {
  return window['go']['main']['App']['UpdateTool'](arg1);
}

export function ValidateClaudeConfig(arg1) {
  return window['go']['main']['App']['ValidateClaudeConfig'](arg1);
}

export function ValidateCodexConfig(arg1) {
  return window['go']['main']['App']['ValidateCodexConfig'](arg1);
}

export function ValidateGeminiConfig(arg1) {
  return window['go']['main']['App']['ValidateGeminiConfig'](arg1);
}

export function ValidateNullClawConfig(arg1) {
  return window['go']['main']['App']['ValidateNullClawConfig'](arg1);
}

export function ValidateOpenClawConfig(arg1) {
  return window['go']['main']['App']['ValidateOpenClawConfig'](arg1);
}

export function ValidatePicoClawConfig(arg1) {
  return window['go']['main']['App']['ValidatePicoClawConfig'](arg1);
}

export function ValidateZeroClawConfig(arg1) {
  return window['go']['main']['App']['ValidateZeroClawConfig'](arg1);
}
