// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {updater} from '../models';
import {installer} from '../models';
import {config} from '../models';
import {proxy} from '../models';
import {toolconfig} from '../models';
import {validator} from '../models';

export function ApplySelfUpdate():Promise<void>;

export function CheckAllUpdates():Promise<Record<string, updater.UpdateInfo>>;

export function CheckBunInstalled():Promise<boolean>;

export function CheckNodeInstalled():Promise<boolean>;

export function CheckSelfUpdate():Promise<updater.UpdateInfo>;

export function ConfigureAllProxy():Promise<Record<string, string>>;

export function DeleteClaudeConfig(arg1:string):Promise<void>;

export function DeleteCodexConfig(arg1:string):Promise<void>;

export function DeleteGeminiConfig(arg1:string):Promise<void>;

export function DetectAllTools():Promise<Record<string, installer.ToolStatus>>;

export function DownloadCodexBinary(arg1:string):Promise<string>;

export function ExportClaudeConfig(arg1:config.ClaudeConfig):Promise<string>;

export function ExportCodexConfig(arg1:config.CodexConfig):Promise<string>;

export function ExportGeminiConfig(arg1:config.GeminiConfig):Promise<Array<string>>;

export function GenerateClaudeConfig(arg1:config.ClaudeConfig):Promise<string>;

export function GenerateCodexConfig(arg1:config.CodexConfig):Promise<string>;

export function GenerateGeminiConfig(arg1:config.GeminiConfig):Promise<string>;

export function GetAllToolConfigPaths():Promise<Record<string, string>>;

export function GetAppVersion():Promise<string>;

export function GetConfigDir():Promise<string>;

export function GetDefaultClaudeConfig():Promise<config.ClaudeConfig>;

export function GetDefaultCodexConfig():Promise<config.CodexConfig>;

export function GetDefaultGeminiConfig():Promise<config.GeminiConfig>;

export function GetProxySettings():Promise<proxy.ProxySettings>;

export function GetToolConfigPath(arg1:string):Promise<string>;

export function InstallAllTools():Promise<Array<installer.InstallResult>>;

export function InstallBun():Promise<string>;

export function InstallTool(arg1:string):Promise<installer.InstallResult>;

export function ListClaudeConfigs():Promise<Array<string>>;

export function ListCodexConfigs():Promise<Array<string>>;

export function ListGeminiConfigs():Promise<Array<string>>;

export function LoadClaudeConfig(arg1:string):Promise<config.ClaudeConfig>;

export function LoadCodexConfig(arg1:string):Promise<config.CodexConfig>;

export function LoadGeminiConfig(arg1:string):Promise<config.GeminiConfig>;

export function OpenConfigDir():Promise<void>;

export function OpenToolConfigDir(arg1:string):Promise<void>;

export function PackageClaudeConfig(arg1:config.ClaudeConfig):Promise<string>;

export function ReadToolConfig(arg1:string):Promise<toolconfig.ToolConfigInfo>;

export function SaveClaudeConfig(arg1:string,arg2:config.ClaudeConfig):Promise<void>;

export function SaveCodexConfig(arg1:string,arg2:config.CodexConfig):Promise<void>;

export function SaveGeminiConfig(arg1:string,arg2:config.GeminiConfig):Promise<void>;

export function SaveProxySettings(arg1:proxy.ProxySettings):Promise<void>;

export function SaveToolConfig(arg1:string,arg2:string):Promise<void>;

export function UpdateAllTools():Promise<Array<installer.InstallResult>>;

export function UpdateTool(arg1:string):Promise<installer.InstallResult>;

export function ValidateClaudeConfig(arg1:config.ClaudeConfig):Promise<validator.ValidationResult>;

export function ValidateCodexConfig(arg1:config.CodexConfig):Promise<validator.ValidationResult>;

export function ValidateGeminiConfig(arg1:config.GeminiConfig):Promise<validator.ValidationResult>;
