// logSource.ts — mode-aware data source for the request-log admin page.
//
// Hub's LogQuery accepts an authoritative time range (StartAt/EndAt) and a
// type filter. Stats and clear-history are not bound on Hub yet — they fall
// off the public surface and the page hides those controls in Reseller mode.

import { GatewayAPI, type GatewayLog, type GatewayLogStat } from './gateway-api'
import { HubListLogs } from '../../wailsjs/go/main/App'

export interface LogFilter {
  page: number
  perPage: number
  username?: string
  model?: string
  tokenName?: string
  channelId?: number
  type?: number
  startTimestamp?: number // unix seconds
  endTimestamp?: number
}

export interface LogSourceCapabilities {
  stats: boolean
  clearHistory: boolean
}

export interface LogSource {
  readonly kind: 'local' | 'hub'
  readonly capabilities: LogSourceCapabilities

  list(filter: LogFilter): Promise<{ items: GatewayLog[]; total: number }>
  stats?(startTs: number, endTs: number): Promise<GatewayLogStat[]>
  clearHistory?(): Promise<void>
}

class LocalLogSource implements LogSource {
  readonly kind = 'local' as const
  readonly capabilities: LogSourceCapabilities = { stats: true, clearHistory: true }
  private api: GatewayAPI

  constructor(baseURL: string, token: string) {
    this.api = new GatewayAPI(baseURL, token)
  }

  async list(f: LogFilter) {
    const params: Record<string, unknown> = {}
    if (f.username) params.username = f.username
    if (f.model) params.model = f.model
    if (f.tokenName) params.token_name = f.tokenName
    if (f.channelId !== undefined) params.channel_id = f.channelId
    if (f.startTimestamp !== undefined) params.start_timestamp = f.startTimestamp
    if (f.endTimestamp !== undefined) params.end_timestamp = f.endTimestamp
    if (f.type !== undefined) params.type = f.type
    const res = await this.api.getLogs(f.page, f.perPage, params as Parameters<GatewayAPI['getLogs']>[2])
    const items = res.data ?? []
    return { items, total: items.length }
  }

  async stats(startTs: number, endTs: number) {
    const r = await this.api.getLogStats(startTs, endTs)
    return r.data ?? []
  }

  async clearHistory() {
    await this.api.clearLogs()
  }
}

class HubLogSource implements LogSource {
  readonly kind = 'hub' as const
  readonly capabilities: LogSourceCapabilities = { stats: false, clearHistory: false }

  async list(f: LogFilter) {
    // Hub's LogQuery is the Go struct shape generated by Wails — field names
    // are PascalCase. Time fields are Go time.Time → ISO strings.
    const query: Record<string, unknown> = {
      Page: f.page + 1, // Hub is 1-indexed
      PageSize: f.perPage,
      Username: f.username ?? '',
      TokenName: f.tokenName ?? '',
      ModelName: f.model ?? '',
      Type: f.type ?? 0,
      ChannelID: f.channelId ?? 0,
      Group: '',
      IP: '',
      OnlyMine: false,
    }
    if (f.startTimestamp !== undefined) {
      query.StartAt = new Date(f.startTimestamp * 1000).toISOString()
    }
    if (f.endTimestamp !== undefined) {
      query.EndAt = new Date(f.endTimestamp * 1000).toISOString()
    }
    // The Wails-generated parameter is a class but the runtime accepts a
    // plain object — cast through `any` to skip the constructor.
    const resp = await HubListLogs(query as never)
    // Hub returns LogEntry, frontend uses GatewayLog. The relevant fields
    // (id, user_id, username, model_name, channel, etc.) overlap; we map
    // model_name → model and channel → channel_id for compatibility.
    const items = (resp.items ?? []).map((e) => ({
      id: e.id,
      user_id: e.user_id,
      created_at: e.created_at,
      type: e.type,
      content: e.content,
      username: e.username,
      token_name: e.token_name,
      model: e.model_name,
      quota: e.quota,
      prompt_tokens: e.prompt_tokens,
      completion_tokens: e.completion_tokens,
      channel_id: e.channel,
      channel_name: '',
    })) as GatewayLog[]
    return { items, total: resp.total ?? 0 }
  }
}

export type { GatewayLog, GatewayLogStat } from './gateway-api'

export function makeLogSource(args:
  | { mode: 'local'; baseURL: string; token: string }
  | { mode: 'hub' }
): LogSource {
  if (args.mode === 'hub') return new HubLogSource()
  return new LocalLogSource(args.baseURL, args.token)
}
